version: '3.8'

services:
  web:
    image: training_tools:latest
    container_name: training_tools_app
    build:
      context: .
      dockerfile: ./src/WebUI/Dockerfile
    ports:
      - "8020:8080"
      - "8021:8081"
    depends_on:
      - mssql
      
    networks:
      - training_tools_network

  mssql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: training_tools_mssql
    environment:
      - SA_PASSWORD=DbPass20190502
      - ACCEPT_EULA=Y
    ports:
      - "8010:1433"
    volumes:
      - mssql_data:/var/opt/mssql
      - D:\Programming\Databases\Backups:/backups
    networks:
      - training_tools_network

networks:
  training_tools_network:
    driver: bridge

volumes:
  mssql_data: