services:
  web:
    image: training_tools:latest
    container_name: training_tools_app
    build:
      context: .
      dockerfile: ./src/WebUI/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ActiveConnection=DockerDatabase
      - RazorRuntimeCompilation=false
      - ASPNETCORE_HTTP_PORTS=8080
      - ASPNETCORE_HTTPS_PORTS=8081
    ports:
      - "8020:8080"
      - "8021:8081"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro